import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import ts from "typescript";
import YAML from "yaml";

const root = process.cwd();
const localesRoot = path.join(root, "src", "i18n", "locales");
const output = path.join(root, "src", "i18n", "catalogs.generated.ts");

const fail = (message) => {
  throw new Error(`i18n: ${message}`);
};

const flatten = (value, prefix = "") => {
  if (!value || typeof value !== "object" || Array.isArray(value))
    fail(`${prefix || "catalog"} must be a mapping.`);
  return Object.entries(value).reduce((catalog, [key, child]) => {
    if (key.includes("."))
      fail(
        `${prefix ? `${prefix}.` : ""}${key} must use nested YAML mappings, not a dotted key.`,
      );
    const name = prefix ? `${prefix}.${key}` : key;
    if (typeof child === "string") {
      if (!child.trim()) fail(`${name} must not be blank.`);
      catalog[name] = child;
      return catalog;
    }
    Object.assign(catalog, flatten(child, name));
    return catalog;
  }, {});
};

const localeFiles = (await readdir(localesRoot))
  .filter((file) => file.endsWith(".yml") || file.endsWith(".yaml"))
  .sort();
if (!localeFiles.includes("en.yml"))
  fail("src/i18n/locales/en.yml is required.");

const catalogs = Object.fromEntries(
  await Promise.all(
    localeFiles.map(async (file) => {
      const locale = path.basename(file, path.extname(file));
      const source = await readFile(path.join(localesRoot, file), "utf8");
      return [locale, flatten(YAML.parse(source))];
    }),
  ),
);
const english = catalogs.en;
const keys = Object.keys(english).sort();
if (!keys.length) fail("English catalog must not be empty.");
const placeholders = (message) =>
  [...message.matchAll(/\{([a-zA-Z][\w]*)\}/g)]
    .map((match) => match[1])
    .sort()
    .join(",");

for (const [locale, catalog] of Object.entries(catalogs)) {
  const actual = Object.keys(catalog).sort();
  const missing = keys.filter((key) => !actual.includes(key));
  const extra = actual.filter((key) => !keys.includes(key));
  if (missing.length || extra.length)
    fail(
      `${locale} catalog differs from en.yml: ${[
        missing.length ? `missing ${missing.join(", ")}` : "",
        extra.length ? `extra ${extra.join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("; ")}.`,
    );
  if (locale !== "en")
    for (const key of keys)
      if (catalog[key] === english[key])
        fail(`${locale}.${key} is identical to the English source.`);
      else if (placeholders(catalog[key]) !== placeholders(english[key]))
        fail(`${locale}.${key} does not preserve English placeholders.`);
}

const sourceFiles = [];
const collectSources = async (directory) => {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) await collectSources(file);
    else if (entry.isFile() && entry.name.endsWith(".ts") && file !== output)
      sourceFiles.push(file);
  }
};
await collectSources(path.join(root, "src"));

const used = new Set();
for (const file of sourceFiles) {
  const source = ts.createSourceFile(
    file,
    await readFile(file, "utf8"),
    ts.ScriptTarget.Latest,
    true,
  );
  const visit = (node) => {
    if (ts.isStringLiteral(node) && keys.includes(node.text))
      used.add(node.text);
    ts.forEachChild(node, visit);
  };
  visit(source);
}
const unused = keys.filter((key) => !used.has(key));
if (unused.length) fail(`unused message keys: ${unused.join(", ")}.`);

const ordered = Object.fromEntries(
  Object.entries(catalogs).map(([locale, catalog]) => [
    locale,
    Object.fromEntries(keys.map((key) => [key, catalog[key]])),
  ]),
);
const generated = `// Generated by scripts/generate-i18n.mjs. Do not edit manually.\nexport const catalogs = ${JSON.stringify(ordered, null, 2)} as const;\n\nexport type Locale = keyof typeof catalogs;\nexport type MessageKey = keyof typeof catalogs.en;\n`;
await mkdir(path.dirname(output), { recursive: true });
await writeFile(output, generated);
